# Generated by Django 6.0.1 on 2026-01-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='qtype',
            field=models.CharField(choices=[('radios', 'Radios'), ('inline', 'Inline'), ('inline_tab', 'Inline Tab')]),
        ),
    ]
