# Generated by Django 6.0.1 on 2026-01-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_test_qtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='qtype',
            field=models.CharField(choices=[('radios', 'Radios'), ('inline', 'Inline'), ('inline_tab', 'Inline Tab'), ('checkbox', 'Checkbox'), ('tabular', 'Tabular')]),
        ),
    ]
