# Generated by Django 6.0.1 on 2026-01-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_test_qtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='jsondata',
            field=models.JSONField(default=dict),
        ),
    ]
