# Generated by Django 6.0.1 on 2026-01-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_test_jsondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='jsondata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='qtype',
            field=models.CharField(choices=[('radios', 'Radios'), ('inline', 'Inline'), ('inline_tab', 'Inline Tab'), ('checkbox', 'Checkbox'), ('tabular', 'Tabular'), ('grid', 'Grid (JSON)')]),
        ),
        migrations.AlterField(
            model_name='test',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
