# Generated by Django 6.0.1 on 2026-01-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_test_jsondata_alter_test_qtype_alter_test_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='jsondata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
