# Generated by Django 6.0.1 on 2026-01-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_test_jsondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='jsondata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
