# Generated by Django 6.0.1 on 2026-02-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_test_jsondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='qtype',
            field=models.CharField(choices=[('radios', 'Radios'), ('inline', 'Inline'), ('inline_tab', 'Inline Tab'), ('checkbox', 'Checkbox'), ('tabular', 'Tabular (JSON)'), ('grid', 'Grid (JSON)'), ('assign', 'Assign (JSON)')]),
        ),
    ]
