# Generated by Django 6.0.1 on 2026-02-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_test_qtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='qtype',
            field=models.CharField(choices=[('radios', 'Radios'), ('inline', 'Inline'), ('inline_list', 'Inline List'), ('inline_tab', 'Inline Tab'), ('checkbox', 'Checkbox'), ('tabular', 'Tabular (JSON)'), ('grid', 'Grid (JSON)'), ('assign', 'Assign (JSON)'), ('draganddrop', 'Drag-and-Drop (JSON)')]),
        ),
    ]
