# Generated by Django 6.0.1 on 2026-02-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_test_qtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='jsondata',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='test',
            name='text',
        ),
        migrations.AlterField(
            model_name='test',
            name='qtype',
            field=models.CharField(choices=[('radios', 'Radios'), ('inline', 'Inline'), ('inline_list', 'Inline List'), ('inline_tab', 'Inline Tab'), ('checkbox', 'Checkbox'), ('tabular', 'Tabular'), ('grid', 'Grid'), ('assign', 'Assign'), ('draganddrop', 'Drag-and-Drop')]),
        ),
    ]
