# Generated by Django 6.0.1 on 2026-03-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_rename_jsondata_test_data_remove_test_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
